drop table if exists user CASCADE;
create table user (

    id bigint generated by default as identity,

    firstName varchar(255),
    lastName varchar(255),
    email char(50),
    password char(50),
    phoneNumber(50)

    primary key (user_id)
);